/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.Component;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.User;

/**
 *
 * @author wolves
 */
public class FormJPanel extends javax.swing.JPanel {
    
    private JPanel bottomPanel;
    private ImageIcon picture;
    private JLabel imageLabel;
    
   

    /**
     * Creates new form FormJPanel
     */
   public FormJPanel() {
        initComponents();
    }
    
    public FormJPanel(JPanel bottomPanel){
        initComponents();
    this.bottomPanel = bottomPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameTextField = new javax.swing.JTextField();
        name = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        ComboBox = new javax.swing.JComboBox<>();
        hobby = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        hobbiesTextArea = new javax.swing.JTextArea();
        uploadButton = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();
        ageSpinner = new javax.swing.JSpinner();
        phoneNumberInputField = new javax.swing.JTextField();
        surnameInputField = new javax.swing.JTextField();
        surname = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        emailInputField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 255));

        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        name.setText("Name");

        jLabel1.setText("Email");

        gender.setText("Gender");

        ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        hobby.setText("Hobby");

        hobbiesTextArea.setColumns(20);
        hobbiesTextArea.setRows(5);
        jScrollPane1.setViewportView(hobbiesTextArea);

        uploadButton.setText("Upload Photo");
        uploadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadButtonActionPerformed(evt);
            }
        });

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        ageSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        surname.setText("Surname");

        jLabel3.setText("Phone Number");

        jLabel4.setText("Age");

        jLabel2.setFont(new java.awt.Font("Apple Chancery", 3, 36)); // NOI18N
        jLabel2.setText("Registration");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(hobby)
                        .addGap(56, 56, 56)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(emailInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(205, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uploadButton)
                            .addGap(212, 212, 212))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(name))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(gender)))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(161, 161, 161)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(submitButton)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(62, 62, 62))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 231, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(surname, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3))
                                        .addComponent(jLabel4))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(surnameInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(phoneNumberInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ageSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(167, Short.MAX_VALUE)
                .addComponent(emailInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(hobby)
                        .addGap(156, 156, 156))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2)
                    .addGap(27, 27, 27)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(surnameInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(surname))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(47, 47, 47)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3)
                                .addComponent(phoneNumberInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(43, 43, 43)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(gender)
                                .addComponent(jLabel4)
                                .addComponent(ageSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                    .addComponent(uploadButton)
                    .addGap(35, 35, 35)
                    .addComponent(submitButton)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void uploadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadButtonActionPerformed
        // TODO add your handling code here:
        //handle image upload
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
            "Image Files", "jpeg", "png", "gif"
        );
        fileChooser.setFileFilter(filter);

        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {

            try {
                File selectedFile = fileChooser.getSelectedFile();
                BufferedImage img = ImageIO.read(selectedFile);
                Image scaledImage =  img.getScaledInstance(60, 80, Image.SCALE_SMOOTH);

                ImageIcon userProfilePic = new ImageIcon(scaledImage);
                imageLabel.setIcon(userProfilePic); //image preview
                imageLabel.setText("");

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this,"Please upload image correctly","Error - Incorrect image",JOptionPane.ERROR_MESSAGE);

                ex.printStackTrace();
            }
        }

    }//GEN-LAST:event_uploadButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed

        // TODO add your handling code here:
        //1. Get the user details (name & college
            try {
                // Initialize object of User class
                User userObject = new User();

                // Set values from UI components directly into the User object
                userObject.setName(nameTextField.getText().trim());
                userObject.setSurname(surnameInputField.getText().trim());
                userObject.setEmail(emailInputField.getText().trim());
                userObject.setPhoneNumber(phoneNumberInputField.getText().trim());
                userObject.setGender((String) ComboBox.getSelectedItem());
                userObject.setAge((Integer) ageSpinner.getValue());
                userObject.setHoby(hobbiesTextArea.getText().trim());

                System.out.println(userObject.getName());
                System.out.println(userObject.getSurname());
                System.out.println(userObject.getEmail());
                System.out.println(userObject.getPhoneNumber());
                System.out.println(userObject.getGender());
                System.out.println(userObject.getAge());
                System.out.println(userObject.getHoby());
                Component rootPane = null;

                // Validation

                if( userObject.getName().isEmpty()){
                    JOptionPane.showMessageDialog(rootPane,"Please enter name.", "Oops", JOptionPane.ERROR_MESSAGE);
                    return;

                }

                if(userObject.getSurname().isEmpty()){
                    JOptionPane.showMessageDialog(rootPane,"Please enter surnaname.", "Oops", JOptionPane.ERROR_MESSAGE);
                    return;

                }

                if(userObject.getEmail().isEmpty()){
                    JOptionPane.showMessageDialog(rootPane,"Invalid email format (must contain @ and domain", "Oops", JOptionPane.ERROR_MESSAGE);
                    return;

                }

                if (!isValidEmail(userObject.getEmail())) {
                    JOptionPane.showMessageDialog(rootPane, "Invalid email format", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                if(userObject.getPhoneNumber().isEmpty()){
                    JOptionPane.showMessageDialog(rootPane,"Please enter phoneNumber.", "Oops", JOptionPane.ERROR_MESSAGE);
                    return;

                }

                if(userObject.getEmail().isEmpty()){
                    JOptionPane.showMessageDialog(rootPane,"Please enter hobies.", "Oops", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                if(userObject.getAge() <=0 ){
                    JOptionPane.showMessageDialog(rootPane,"Please select a valid age.", "Oops", JOptionPane.ERROR_MESSAGE);
                    return;

                }

                JOptionPane.showMessageDialog(rootPane,  """
                    Registration Successful! User Details:   %s""".formatted(userObject), "Success", JOptionPane.INFORMATION_MESSAGE
                );

            }
            catch (NullPointerException ne) {
                Component rootPane = null;
                JOptionPane.showMessageDialog(rootPane,"Please fill all fields", "Oops", JOptionPane.ERROR_MESSAGE);

            } catch (Exception e){
                Component rootPane = null;
                JOptionPane.showMessageDialog(rootPane,"Oops, omething went wrong", "Failed", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }

    }//GEN-LAST:event_submitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox;
    private javax.swing.JSpinner ageSpinner;
    private javax.swing.JTextField emailInputField;
    private javax.swing.JLabel gender;
    private javax.swing.JTextArea hobbiesTextArea;
    private javax.swing.JLabel hobby;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel name;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField phoneNumberInputField;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel surname;
    private javax.swing.JTextField surnameInputField;
    private javax.swing.JButton uploadButton;
    // End of variables declaration//GEN-END:variables

    private boolean isValidEmail(String email) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
